services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_oqueasy
    ports:
      - '3000:3000'
    depends_on:
      - db

  backend:
    build: .
    container_name: backend_oqueasy
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data2:z
    env_file:
      - .env

volumes:
  postgres_data:
