"""empty message

Revision ID: 7699642713c7
Revises: 4c3f7b27d93f
Create Date: 2025-05-09 10:24:51.727250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7699642713c7'
down_revision: Union[str, None] = '4c3f7b27d93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('topic_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'topic_content')
    # ### end Alembic commands ###
