"""empty message

Revision ID: a94b300f7924
Revises: 7699642713c7
Create Date: 2025-05-09 10:26:23.755389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94b300f7924'
down_revision: Union[str, None] = '7699642713c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('topic_content', sa.Text(), nullable=False))
    op.drop_column('topic', 'topic_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('topic_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('content', 'topic_content')
    # ### end Alembic commands ###
